apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devsecops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ahmed1707hamed-tech/devsecOps_project.git
    targetRevision: main
    path: helm/devsecops

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true