apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devsecops-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: devsecops-backend
      rules:

        - alert: BackendDown
          expr: up{job="devsecops-backend"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "DevSecOps Backend is down"
            description: "Backend instance {{ $labels.instance }} has been down for more than 1 minute."

        - alert: BackendHighCPU
          expr: |
            sum(
              rate(container_cpu_usage_seconds_total{
                namespace="devsecops",
                pod=~"devsecops-backend-.*",
                container="backend"
              }[5m])
            ) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Backend CPU usage is high"
            description: "DevSecOps backend CPU usage is above 80%."

        - alert: BackendHighMemory
          expr: |
            sum(
              container_memory_working_set_bytes{
                namespace="devsecops",
                pod=~"devsecops-backend-.*",
                container="backend"
              }
            ) / 1024 / 1024 > 500
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Backend memory usage is high"
            description: "DevSecOps backend memory usage is above 500 MB."

        - alert: BackendHighLatency
          expr: |
            histogram_quantile(
              0.95,
              sum(
                rate(http_request_duration_seconds_bucket{
                  job="devsecops-backend"
                }[5m])
              ) by (le)
            ) > 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Backend latency is high"
            description: "95th percentile backend request latency is above 1 second."